luxmind/client/urls.py
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'client'
urlpatterns = [
    
    path('', views.Front_page,name='Front_page'),
    path('Register', views.Register_page,name='Register_page'),
    path('Forgot_Password', views.ForgotPassword,name='ForgotPassword'),
    path('Change_Password', views.ChangePassword,name='ChangePassword'),
    path('logout_urequest', views.logout_urequest,name='logout_urequest'),
    path('CreateClient', views.CreateClient,name='CreateClient'),
    path('LoginClient', views.LoginClient,name='LoginClient'),
    path('Dashboard', views.Dashboard,name='Dashboard'),
    path('FreeEnquiry', views.FreeEnquiry,name='FreeEnquiry'),
    path('OrderPaper', views.OrderPaper,name='OrderPaper'),
    path('UpdatePaper', views.UpdatePaper,name='UpdatePaper'),
    path('UpdatePaper1', views.UpdatePaper1,name='UpdatePaper1'),
    path('UpdatePaper2', views.UpdatePaper2,name='UpdatePaper2'),
    path('upload_file', views.upload_file,name='upload_file'),
    path('PlaceOrder', views.Place_Order,name='Place_Order'),
    path('PlaceEnquiry', views.PlaceEnquiry,name='PlaceEnquiry'),
    path('View/Order/<int:id>', views.View_Order,name='View_Order'),
    path('CSendMessage', views.CSendMessage,name='CSendMessage'),
    path('CompleteOrder/<int:id>', views.CompleteOrder,name='CompleteOrder'),
    path('RaiseDispute', views.RaiseDispute,name='RaiseDispute'),
    path('ImportData', views.ImportData,name='ImportData'),
    path('post_messages', views.post_messages,name='post_messages'),


]

luxmind/luxmind/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve 


urlpatterns = [
    path('admin/', admin.site.urls),   
    path('luxmind/', include('kadmin.urls')),
    path('', include('client.urls')),
    path('Tutor/', include('tutor.urls')),
    
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

# handler404 = 'client.views.custom_page_not_found_view'
# handler500 = 'client.views.custom_error_view'
# handler403 = 'client.views.custom_permission_denied_view'
# handler400 = 'client.views.custom_bad_request_view'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

luxmind/tutor/urls.py
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    

    path('', views.TutorFront_page,name='TutorFront_page'),
    path('LoginTutor', views.LoginTutor,name='LoginTutor'),
    path('ForgotPassword', views.ForgotPassword,name='ForgotPassword'),
    path('logout_request', views.logout_request,name='logout_request'),
    path('TutorChangePassword', views.TutorChangePassword,name='TutorChangePassword'),
    path('New', views.TutorDashboard,name='TutorDashboard'),
    path('Current', views.CurrentPapers,name='CurrentPapers'),
    path('Finished', views.FinishedPaper,name='FinishedPaper'),
    path('Disputes', views.DisputesPaper,name='DisputesPaper'),
    path('Revision', views.RevisionPaper,name='RevisionPaper'),
    path('Bids', views.BidsPapers,name='BidsPapers'),
    path('Paper/<int:id>', views.TutorPaper,name='TutorPaper'),
    path('Create/Account', views.CreateAccount,name='CreateAccount'),
    path('NewAccount', views.NewAccount,name='NewAccount'),
    path('Download/<int:id>', views.DownloadFiles,name='DownloadFiles'),
    path('SendMessage', views.SendMessage,name='SendMessage'),
    path('TakeOrder/<int:id>', views.TakeOrder,name='TakeOrder'),
    path('BidOrder/<int:id>', views.BidOrder,name='BidOrder'),
    path('BidTime/<int:id>', views.BidTime,name='BidTime'),
    path('BidAmount/<int:id>', views.BidAmount,name='BidAmount'),
    path('BidTimeAmount/<int:id>', views.BidTimeAmount,name='BidTimeAmount'),
    path('SubmitOrder/<int:id>', views.SubmitOrder,name='SubmitOrder'),

    path('AcceptBid/<int:id>', views.AcceptBid,name='AcceptBid'),
    path('RejectBid/<int:id>', views.RejectBid,name='RejectBid'),
    path('DeleteFile/<int:id>', views.DeleteFile,name='DeleteFile'),
    path('SubmitFiles', views.SubmitFiles,name='SubmitFiles'),
    
    

]

luxmind/client/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .models import Users, PaperBids, Discipline, TypePaper, TempPaper, Documents, PaperSumation, PricePerDuration, \
    PaperMessage, Messages
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.mail import send_mail
from django.conf import settings
from django.core import mail
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import JsonResponse
import re
import random
import string
import requests
import json
from django.core.exceptions import ObjectDoesNotExist
import json as simplejson
from uuid import getnode as get_mac
from django.db.models import DateField, Sum
from django.http import JsonResponse
from datetime import date
from json import dumps
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
import os
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
import socket
from django.template.loader import render_to_string, get_template
import re
import xlrd
import urllib
import json


def post_messages(request):
    if request.method == "POST":
        to = request.POST['to']
        subject = request.POST['subject']
        message = request.POST['message']
        Messages.objects.create(
            to=to,
            subject=subject,
            message=message,
        )
        messages.success(request, 'Message sent successfully.')
        return redirect('client:OrderPaper')


def trial(request):
    return render(request, 'client/basex.html')


def Front_page(request):
    return render(request, "client/login.html")


def Register_page(request):
    return render(request, "client/register.html")


def ForgotPassword(request):
    return render(request, "client/forgot1.html")


def ChangePassword(request):
    if request.method == "POST":
        email = request.POST['login-email']
        password = random.randint(1000000, 10000000)
        try:
            hy = Users.objects.get(Email=email)
            u = User.objects.get(username=email)
            u.set_password(password)
            u.save()

            message1 = Mail(
                from_email='electromartke@gmail.com',
                # to_emails=['juliuszakora@gmail.com'],
                to_emails=[email],
                subject='Password Reset',

                html_content=("Your New Password is " + str(password)),
            )
            try:
                # sg = SendGridAPIClient('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')
                sg = SendGridAPIClient('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')
                response = sg.send(message1)
                print(response.status_code)
                print(response.body)
                print(response.headers)
            except Exception as e:
                print(e.body)

            messages.error(request, 'Check You Email For the Password')
            return render(request, "client/login.html")
        except ObjectDoesNotExist:
            messages.error(request, 'Email Doesnt Exists')
            return render(request, "client/forgot1.html")


def CreateClient(request):
    if request.method == "POST":
        email = request.POST['register-email']
        Name = request.POST['register-name']
        Password = request.POST['register-password']
        try:
            hy = Users.objects.get(Email=email)
            messages.warning(request, 'Email already Exists')
            return render(request, "client/register.html")
        except ObjectDoesNotExist:
            my_form = Users(Email=email,
                            Name=Name)
            my_form.save()

            User.objects.create_user(username=email, password=Password, email=email)
            messages.success(request, 'Account Created Successfully')
            return HttpResponseRedirect(reverse('client:Front_page'))


def LoginClient(request):
    if request.method == "POST":
        email = request.POST['login-email']
        Password = request.POST['login-password']
        user = authenticate(request, username=email, password=Password)
        if user:
            Name = Users.objects.get(Email=email).Name
            userid = Users.objects.get(Email=email).id
            request.session['Email'] = email
            request.session['Name'] = Name
            request.session['Userid'] = userid
            login(request, user)
            messages.success(request, 'Logged in successfully as ' + request.user.username)
            return HttpResponseRedirect(reverse('client:Dashboard'))
        else:
            messages.warning(request, 'Details Dont Match')
            return HttpResponseRedirect(reverse('client:Front_page'))


def logout_urequest(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return render(request, "client/login.html")


def Dashboard(request):
    Userid = request.session.get('Userid')
    papers = TempPaper.objects.filter(ipaddress=Userid)

    return render(request, "client/dashboard.html", {
        'papers': papers,

    })


def View_Order(request, id):
    Orderid = TempPaper.objects.get(pk=id).Orderid
    papers = TempPaper.objects.get(pk=id)
    messages = PaperMessage.objects.filter(PaperId=id)
    gfiles = Documents.objects.filter(PaperId=Orderid, PaperType="WPaper")
    request.session['Orderid'] = Orderid

    return render(request, "client/vieworder.html", {
        'papers': papers,
        'messages': messages,
        'gfiles': gfiles,

    })


def FreeEnquiry(request):
    paper = TypePaper.objects.all()
    discpline = Discipline.objects.all()
    mac1 = request.session.get('mac')
    if mac1 is None:
        mac = random.randint(1000000, 10000000)
        request.session['mac'] = mac
        Pit = ""
        gfiles = ""
        sums = ""
        dsum = 0
    else:
        mac = mac1
        try:
            Pit = TempPaper.objects.get(ipaddress=mac)
        except ObjectDoesNotExist:
            Pit = ""
        try:
            gfiles = Documents.objects.filter(ipaddress=mac)
        except ObjectDoesNotExist:
            gfiles = ""

        try:
            sums = PaperSumation.objects.filter(ipaddress=mac)
            dsum = PaperSumation.objects.filter(ipaddress=mac).aggregate(Sum('Amount'))['Amount__sum'] or 0
        except ObjectDoesNotExist:
            sums = ""
            dsum = 0

    return render(request, "client/freeenquiry.html", {
        'paper': paper,
        'discpline': discpline,
        'details': Pit,
        'gfiles': gfiles,
        'sums': sums,
        'dsum': round(dsum, 2),
        'gt': range(1, 8),
    })

    # return render(request,"client/freeenquiry.html")


def OrderPaper(request):
    # paper=TypePaper.objects.all()
    # discpline=Discipline.objects.all()
    mac1 = request.session.get('mac')
    if mac1 is None:
        mac = random.randint(1000000, 10000000)
        request.session['mac'] = mac
        Pit = ""
        gfiles = ""
        sums = ""
        dsum = 0
        paper = TypePaper.objects.all()
        discpline = Discipline.objects.all()
    else:
        mac = mac1
        try:
            Pit = TempPaper.objects.get(ipaddress=mac)
            target = TempPaper.objects.get(ipaddress=mac).AcademicLevel
            if target is None:
                paper = TypePaper.objects.all()
                discpline = Discipline.objects.all()
            else:
                if target == "High School":
                    paper = TypePaper.objects.filter(Highschool=1)
                    discpline = Discipline.objects.filter(Highschool=1)
                elif target == "Undergraduate(1-2Yrs)":
                    paper = TypePaper.objects.filter(Undergrad1=1)
                    discpline = Discipline.objects.filter(Undergrad1=1)
                elif target == "Undergraduate(3-4Yrs)":
                    paper = TypePaper.objects.filter(Undergrad2=1)
                    discpline = Discipline.objects.filter(Undergrad2=1)
                elif target == "Graduate":
                    paper = TypePaper.objects.filter(Grad=1)
                    discpline = Discipline.objects.filter(Grad=1)
                else:
                    paper = TypePaper.objects.filter(PHD=1)
                    discpline = Discipline.objects.filter(PHD=1)
        except ObjectDoesNotExist:
            Pit = ""
            paper = TypePaper.objects.all()
            discpline = Discipline.objects.all()
        try:
            gfiles = Documents.objects.filter(ipaddress=mac)
        except ObjectDoesNotExist:
            gfiles = ""

        try:
            sums = PaperSumation.objects.filter(ipaddress=mac)
            dsum = PaperSumation.objects.filter(ipaddress=mac).aggregate(Sum('Amount'))['Amount__sum'] or 0
        except ObjectDoesNotExist:
            sums = ""
            dsum = 0
    all_messages = Messages.objects.all()
    # ToDo should be something like .filter(user=request.user)??
    return render(request, "client/paper.html", {
        'paper': paper,
        'discpline': discpline,
        'details': Pit,
        'gfiles': gfiles,
        'sums': sums,
        'dsum': round(dsum, 2),
        'gt': range(1, 8),
        'all_messages': all_messages,
    })


def PlaceEnquiry(request):
    TypeOfPaper = request.POST['TypeOfPaper']
    Discipline = request.POST['Discipline']
    AcademicLevel = request.POST['AcademicLevel']
    Pages = request.POST['Pages']
    Spacing = request.POST['Spacing']
    Description = request.POST['Description']
    uploaded_files = request.FILES.getlist('myfile')
    mac1 = request.session.get('mac')
    Userid = request.session.get('Userid')

    if mac1 is None:

luxmind/client/templates/client/dashboard.html
{% extends "client/base.html" %}

{% load static  %}

<!-- BEGIN: Content-->
{% block body %}
      {%if messages%}
			<div class="row my-3">
				<div class="col-xl-8 col-sm-6 offset-xl-2 offset-sm-3">
					<div>
						{% for message in messages %}
						  <div class="alert alert-{{message.tags}} alert-dismissible text-center" role="alert">
							{{message}}
							<button type="button" class="close" data-dismiss="alert">
							  <span aria-hidden="true">&times;</span>
							</button>
						  </div>
						{%endfor%}
					 </div>
				</div>
			</div>
        {%endif%}

<!-- end of message div -->

<div class="container-fluid">
	<div class="row my-3">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header header-elements-inline">
						<h6 class="card-title btn btn-primary" style="background:rgb(41,58,89); margin-left:20px; width:150px;">My Orders</h6>
						<div class="header-elements">
							<div class="list-icons">
								<a class="list-icons-item" data-action="collapse"></a>
								<a class="list-icons-item" data-action="reload"></a>
								<a class="list-icons-item" data-action="remove"></a>
							</div>
						</div>
				</div>

				<div class="card-body">
					<div class="d-lg-flex" >
						<ul class="nav nav-pills  flex-column mr-lg-3 wmin-lg-250 mb-lg-0" style="font-size:15px;border-right: 1px solid rgb(240, 234, 234);">
							<li class="nav-item">
								<a href="#stacked-left-pill1" class="nav-link active" data-toggle="tab">
									<i class="fas fa-history"></i> Recent
								</a>
							</li>
							<li class="nav-item">
								<a href="#stacked-left-pill2" class="nav-link" data-toggle="tab">
									<i class="fas fa-check" style="color:green;"></i> Completed
								</a>
							</li>
							<li class="nav-item">
								<a href="#stacked-left-pill3" class="nav-link" data-toggle="tab">
									<i class="fas fa-times" style="color:red;"></i> Canceled
								</a>
							</li>
						</ul>
						<div class="container-fluid">
							<div class="tab-content">
								<div class="tab-pane fade show active" id="stacked-left-pill1">
										 <div class="table-responsive">
										<table class="table table-striped">
											<thead>
											<!-- dummy data -->
												<tr>
													<th>Order</th>
													<th>Paper</th>
													<th>Cost</th>
													<th>View</th>
												</tr>
											</thead>
											<tbody>
												<tr>
													<td>Mark</td>
													<td>Otto</td>
													<td>@mdo</td>
													<td>
														<a class="btn btn-primary btn-sm" href="{% url 'client:OrderPaper' %}">
															<i class="fas fa-eye"></i> View
														</a>
													</td>
												</tr>
												<tr>
													<td>Mark</td>
													<td>Otto</td>
													<td>@TwBootstrap</td>
													<td>
														<a class="btn btn-primary btn-sm" href="{% url 'client:OrderPaper' %}">
															<i class="fas fa-eye"></i> View
														</a>
													</td>
												</tr>
												<tr>
													<td>Jacob</td>
													<td>Thornton</td>
													<td>@fat</td>
													<td><i class="fas fa-plus"></i> </td>
												</tr>
												<tr>
													<td>3</td>
													<td>Larry the Bird</td>
													<td>@twitter</td>
													<td><i class="fas fa-plus"></i> </td>
												</tr>
												<!--/ end of dummy data -->
											</tbody>
										</table>
								</div>
								</div>
								<!-- completed and canceled tabs -->
								<div class="tab-pane fade" id="stacked-left-pill2">
									Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid laeggin.
								</div>

								<div class="tab-pane fade" id="stacked-left-pill3">
									DIY synth PBR banksy irony. Leggings gentrify squid 8-bit cred pitchfork. Williamsburg whatever.
								</div>
								<!-- /completed and canceled tabs -->
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

luxmind/client/templates/client/forgot1.html
{% extends 'client/base.html' %}
{% block body %}


	<!-- Page content -->
	<div class="page-content">

		<!-- Main content -->
		<div class="content-wrapper">

			<!-- Content area -->
			<div class="content d-flex justify-content-center align-items-center">

				<!-- Password recovery form -->
					<div class="card mb-0">
						<div class="card-body">
							<div class="text-center mb-3">
								<i class="icon-spinner11 icon-2x text-warning border-warning border-3 rounded-round p-3 mb-3 mt-1"></i>
								<h5 class="mb-0">Password recovery</h5>
								<span class="d-block text-muted">We'll send you instructions in email</span>
							</div>

							<div class="form-group form-group-feedback form-group-feedback-right">
								<form class="auth-register-form login-form mt-2" action="{% url 'client:ChangePassword'  %}" method="POST">
                                    {% csrf_token %}
									<input class="form-control" id="login-email" required  type="email" name="login-email" placeholder="john@example.com" aria-describedby="login-email" autofocus="" tabindex="1" />
								<div class="form-control-feedback">
									<i class="icon-mail5 text-muted"></i>
								</div>
							    <button type="submit" class="btn my-3 bg-blue btn-block"><i class="icon-spinner11 mr-2"></i> Reset password</button>
								</form>

							</div>

						</div>
					</div>
				<!-- /password recovery form -->

			</div>
			<!-- /content area -->
		</div>
		<!-- /main content -->

	</div>
	<!-- /page content -->
{% endblock %}

luxmind/client/templates/client/login.html
{% extends 'client/base.html' %}
{% block body %}

      {%if messages%}
    <div class="row my-3">
		<div class="col-xl-8 col-sm-6 offset-xl-2 offset-sm-3">
		<div>
			{% for message in messages %}
			  <div class="alert alert-{{message.tags}} alert-dismissible text-center" role="alert">
				{{message}}
				<button type="button" class="close" data-dismiss="alert">
				  <span aria-hidden="true">&times;</span>
				</button>
			  </div>
			{%endfor%}
		 </div>
		</div>
    </div>
        {%endif%}
	<!-- Page content -->
	<div class="page-content">

		<!-- Main content -->
		<div class="content-wrapper">

			<!-- Content area -->
			<div class="content d-flex justify-content-center align-items-center">


				<!-- Login form -->
				<form class="auth-register-form mt-2 login-form" action="{% url 'client:LoginClient'  %}" method="POST">
					{% csrf_token %}
					<div class="card mb-0">
						<div class="card-body">
							<div class="text-center mb-3">
								<i class="icon-reading icon-2x text-slate-300 border-slate-300 border-3 rounded-round p-3 mb-3 mt-1"></i>
								<h5 class="mb-0">Login to your account</h5>
								<span class="d-block text-muted">Enter your credentials below</span>
							</div>

							<div class="form-group form-group-feedback form-group-feedback-left">
                                <input class="form-control" id="login-email" type="email" name="login-email" required placeholder="john@example.com" aria-describedby="login-email" autofocus="" tabindex="1" />
								<div class="form-control-feedback">
									<i class="icon-user text-muted"></i>
								</div>
							</div>

							<div class="form-group form-group-feedback form-group-feedback-left">
								<input class="form-control form-control-merge" id="login-password" required type="password" name="login-password" placeholder="············" aria-describedby="login-password" tabindex="2" />
								<div class="form-control-feedback">
									<i class="icon-lock2 text-muted"></i>
								</div>
							</div>

							<div class="form-group">
								<button type="submit" class="btn btn-primary btn-block">Sign in <i class="icon-circle-right2 ml-2"></i></button>
							</div>

							<div class="text-center">
								<a href="{% url 'client:ForgotPassword' %}">Forgot password?</a> <br>
								<a href="{% url 'client:Register_page' %}">Create an Account?</a>

							</div>
						</div>
					</div>
				</form>
				<!-- /login form -->

			</div>
			<!-- /content area -->


		</div>
		<!-- /main content -->

	</div>
	<!-- /page content -->



{% endblock %}

luxmind/client/templates/client/register.html
{% extends 'client/base.html' %}
{% block body %}
      {%if messages%}
			<div class="row my-3">
				<div class="col-xl-8 col-sm-6 offset-xl-2 offset-sm-3">
				<div>
					{% for message in messages %}
					  <div class="alert alert-{{message.tags}} alert-dismissible text-center" role="alert">
						{{message}}
						<button type="button" class="close" data-dismiss="alert">
						  <span aria-hidden="true">&times;</span>
						</button>
					  </div>
					{%endfor%}
				 </div>
				</div>
			</div>
        {%endif%}
	<!-- Page content -->
	<div class="page-content">

		<!-- Main content -->
		<div class="content-wrapper">

			<!-- Content area -->
			<div class="content d-flex justify-content-center align-items-center">

				<!-- Registration form -->
                    <form class="auth-register-form mt-2 login-form" action="{% url 'client:CreateClient'  %}" method="POST">

					<div class="card mb-0">
						<div class="card-body">
                                {% csrf_token %}

								<div class="text-center mb-3">
									<i class="icon-plus3 icon-2x text-success border-success border-3 rounded-round p-3 mb-3 mt-1"></i>
									<h5 class="mb-0">Create account</h5>
								</div>

								<div class="form-group text-center text-muted content-divider">
									<span class="px-2">Your credentials</span>
								</div>

								<div class="form-group form-group-feedback form-group-feedback-left">
									<input class="form-control" required id="register-username" type="text" name="register-name" placeholder="johndoe" aria-describedby="register-username" autofocus="" tabindex="1" />
									<div class="form-control-feedback">
										<i class="icon-user-check text-muted"></i>
									</div>
								</div>

								<div class="form-group form-group-feedback form-group-feedback-left">
									<input class="form-control form-control-merge" required id="register-password" type="password" name="register-password" placeholder="············" aria-describedby="register-password" tabindex="3" />
									<div class="form-control-feedback">
										<i class="icon-user-lock text-muted"></i>
									</div>
								</div>

								<div class="form-group text-center text-muted content-divider">
									<span class="px-2">Your contacts</span>
								</div>

								<div class="form-group form-group-feedback form-group-feedback-left">
									<input class="form-control" required id="register-email" type="text" name="register-email" placeholder="john@example.com" aria-describedby="register-email" tabindex="2" />
									<div class="form-control-feedback">
										<i class="icon-mention text-muted"></i>
									</div>
								</div>
								<div class="form-group text-center text-muted content-divider">
									<span class="px-2">Additions</span>
								</div>

									<div class="form-group">
										<div class="custom-control custom-checkbox">
											<input class="custom-control-input" id="register-privacy-policy"
												type="checkbox" tabindex="4" />
											<label class="custom-control-label" for="register-privacy-policy">I agree
												to<a href="javascript:void(0);">&nbsp;privacy policy & terms</a></label>
										</div>
									</div>
								<button class="btn bg-teal-400 btn-block">Register <i class="icon-circle-right2 ml-2"></i></button> <br>
								<p style="text-align:center;"> Alread have an account? <a href="{% url 'client:Front_page' %}">Sign in</a> </p>
						</div>
					</div>
				</form>
				<!-- /registration form -->

			</div>
			<!-- /content area -->

		</div>
		<!-- /main content -->

	</div>
{% endblock %}